source 'http://rubygems.org'

gem 'activerecord', '4.2', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'

gem 'sinatra'
gem 'sqlite3', '~>1.3.6'
gem 'tux'
gem 'pry'
gem 'pry-nav'
gem 'rake'
# gem 'rack', '~> 1.6', '>= 1.6.4'
gem 'bigdecimal', '~> 1.2', '>= 1.2.7'
gem 'rspec'
gem 'rack-test'
gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
gem 'require_all'
